spring:
  application:
    name: hr-ops-service
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hr_ops_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

server:
  port: 8085

registry:
  enabled: true
  url: ${REGISTRY_URL:http://localhost:8761}
  service-name: hr-ops-service
  service-url: ${SERVICE_URL:http://localhost:8085}

logging:
  level:
    root: INFO
    com.fms.hr_crm: DEBUG

